### ISSUE TITLE
Build with Go v1.17 to support legacy OS X

### ISSUE THREAD

**Issue by alanhamlett** [wakatime/wakatime-cli#732]
Due to https://github.com/golang/go/issues/50855#issuecomment-1023868827, binaries built with Go 1.18 won't run on old OS X versions. We could add a build to the release `wakatime-cli-darwin-amd64-go1.17.zip` and download that when the plugins detect a legacy OS X version.

When running wakatime-cli built with Go 1.18 on legacy OS X we get this error:
```
dyld: Symbol not found: _utimensat
  Referenced from: /Users/user/.wakatime/wakatime-cli
  Expected in: flat namespace
```

**Comment by alanhamlett** [comment]
Instead of building with legacy Go (we depend on new features in Go 1.18) we're going to modify editor extensions to detect legacy OS X platforms and download an old wakatime-cli release. For now, we're implementing this in [Xcode](https://github.com/wakatime/xcode-wakatime/issues/66), [VS Code](https://github.com/wakatime/vscode-wakatime/issues/278), and [Sublime Text](https://github.com/wakatime/sublime-wakatime/issues/114) but can add support to more editor plugins if requested.
